export default {
  HOME: 'HOME',
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  HOME_PAGE: 'HOME_PAGE',
  CREATE_A_PLAAN: 'CREATE_A_PLAAN',
  VIEW_SPECIFIC_PLAN: 'VIEW_SPECIFIC_PLAN',
  FUND_PLAN: 'FUND_PLAN',
};
